title: Security Research Blog
description: Your daily source for security news and research.
url: https://harmen.dev
twitter_username: harmendewit
keywords: security, research, blog, cybersecurity

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag